language: nix
os:
  - linux
env:
  - EMACS_CI=emacs-25-2
  - EMACS_CI=emacs-25-3
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-2
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot
matrix:
  allow_failures:
    - env: EMACS_CI=emacs-snapshot
install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
script:
  - emacs --version
  - make
